name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CI: true

    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 20
        experimental: [false]
        include:
          - node-version: lts/*
            experimental: true

    continue-on-error: ${{ matrix.experimental }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.node-version }}-${{ matrix.experimental }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check repository dependency graph
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        if: ${{ github.event_name == 'pull_request' }}

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: NPM config
        run: |
          npm pkg delete scripts.prepare
          npm install --ignore-scripts --pure-lockfile

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm run test --if-present
